import Foundation

let chartBook: [ChartSpec] = chartBookA + chartBookB + chartBookC

let chartBookA: [ChartSpec] = [
    ChartSpec(id: "carrick_bay", name: "Carrick Bay", place: "Western coast", year: "1841",
              kind: "bay", scaleNote: "Cables", kicker: "Sheet I",
              notes: [("Everything begins with one measured line",
                       "A survey has exactly one measured distance in it. The baseline is chained along flat ground, sometimes for miles, with the chain supported and its temperature noted, and every other distance on the sheet is calculated from it by triangles."),
                      ("Why a bay is hard",
                       "The head of a bay is out of sight of the entrance, so no single station sees it all. The work is a chain of triangles carried round the shore until it closes back on itself, and the error of the whole survey is what it fails to close by.")]),
    ChartSpec(id: "ossary_island", name: "Ossary Island", place: "Outer approaches", year: "1838",
              kind: "island", scaleNote: "Cables", kicker: "Sheet II",
              notes: [("Resection: the three-point problem",
                       "Standing on unknown ground with three known points in sight, measure the two angles between them and the station fixes itself. It is the surveyor's way home when he does not know where he is."),
                      ("The danger circle",
                       "If the observer happens to stand on the circle through all three points, the angles are the same everywhere on it and the fix is worthless. Every textbook warns of it and every surveyor has done it once.")]),
    ChartSpec(id: "mardle_estuary", name: "Mardle Estuary", place: "Tidal reaches", year: "1846",
              kind: "estuary", scaleNote: "Cables", kicker: "Sheet III",
              notes: [("A chart has two shorelines",
                       "High water and low water, and between them the drying banks shown by stipple. In an estuary the difference can be a mile of ground that is land twice a day and sea twice a day."),
                      ("Chart datum",
                       "Soundings are reduced to the lowest tide reasonably expected, so a mariner reading four fathoms will rarely find less. Heights on the same sheet are reckoned from a different level entirely, which has drowned people who forgot it.")]),
    ChartSpec(id: "black_head", name: "Black Head", place: "Northern seaboard", year: "1852",
              kind: "cape", scaleNote: "Sea miles", kicker: "Sheet IV",
              notes: [("Hachures run with the water",
                       "Each stroke lies along the line a drop of water would take. Steep ground gets short, thick, crowded strokes; gentle ground gets long, fine, open ones. Read a hachured hill and you are reading its slope, not its height."),
                      ("Why contours won",
                       "Hachures darken exactly where a map most needs to carry names and detail, and they cannot be measured. Contours say less at a glance and far more to an engineer, and by 1900 they had taken over.")]),
    ChartSpec(id: "wrenport", name: "Wrenport Harbour", place: "Packet station", year: "1859",
              kind: "harbour", scaleNote: "Cables", kicker: "Sheet V",
              notes: [("Leading marks",
                       "Two objects in line give a bearing more exactly than any compass. A harbour survey looks for them — a chapel over a jetty head, one rock touching another — and prints them as a transit line on the chart."),
                      ("The plan is drawn for one reader",
                       "Not a traveller but a master coming in at night with a leadsman in the chains. Everything on a harbour plan is there to answer where is the water and what will I strike.")]),
    ChartSpec(id: "loch_tarbh", name: "Loch Tarbh", place: "Sea loch", year: "1848",
              kind: "loch", scaleNote: "Cables", kicker: "Sheet VI",
              notes: [("Sounding by lead line",
                       "A boat rows a straight line between two fixed marks while the leadsman calls and the officer fixes the boat by sextant angles to the shore. Every number on the chart was once a wet rope and a shout."),
                      ("Interlining",
                       "The lines of soundings are run close enough that nothing dangerous can hide between them. Where the bottom is rocky and irregular the lines are halved, and halved again, until the pattern stops surprising anybody.")]),
    ChartSpec(id: "thrift_sands", name: "Thrift Sands", place: "Outer bank", year: "1843",
              kind: "bay", scaleNote: "Sea miles", kicker: "Sheet VII",
              notes: [("Banks move",
                       "A sandbank surveyed one decade is not where the chart says the next. The date in the cartouche is not decoration; it is a warning about how much of this sheet you should still believe."),
                      ("Stipple and the drying height",
                       "A stippled bank carries a figure with a line under it: the height it dries above chart datum. Read without the underline it looks like a sounding, and the ship goes on.")]),
    ChartSpec(id: "crag_sound", name: "Crag Sound", place: "Inner passage", year: "1855",
              kind: "sound", scaleNote: "Cables", kicker: "Sheet VIII",
              notes: [("Tidal streams",
                       "A sound runs like a river and turns twice a day. Arrows on the chart give the direction and the rate at springs, taken from a boat anchored for a whole tide with a log line over the side."),
                      ("Overfalls",
                       "Where a stream runs over an uneven bottom the sea breaks in a calm. The symbol is a short row of ripples, and it means take this seriously in a small boat.")]),
]

let chartBookB: [ChartSpec] = [
    ChartSpec(id: "sker_reef", name: "Sker Reef", place: "Offshore dangers", year: "1861",
              kind: "reef", scaleNote: "Sea miles", kicker: "Sheet IX",
              notes: [("Rocks have three symbols",
                       "A cross for a rock that never covers, a cross with dots for one that covers and uncovers, and a dotted circle for one whose exact place nobody is sure of. The third is the one that frightens surveyors."),
                      ("Sweeping",
                       "To prove a rock is not there, two boats drag a wire between them at a set depth across the whole area. It is slow, dull, expensive work and it is the only thing that turns a doubtful danger into a cleared one.")]),
    ChartSpec(id: "dunmore_haven", name: "Dunmore Haven", place: "Fishing haven", year: "1857",
              kind: "harbour", scaleNote: "Cables", kicker: "Sheet X",
              notes: [("Names are collected, not invented",
                       "The surveyor writes down what the people on the shore call each rock and gully, and spells it as best he can. Half the odd names on any coastal chart are a mishearing that outlived the man who made it."),
                      ("The name orders the chart",
                       "Upright letters for what is dry, sloping letters for what is wet. That single convention lets a reader tell a sandbank from a village without reading a word.")]),
    ChartSpec(id: "glass_water", name: "The Glass Water", place: "Inland water", year: "1850",
              kind: "loch", scaleNote: "Furlongs", kicker: "Sheet XI",
              notes: [("A plane table draws itself",
                       "A drawing board on a tripod, a sheet pinned to it and a sighted rule. Point the rule at the object, draw the ray, move to the next station, draw again, and the intersection is the object's place. No angles are ever written down."),
                      ("Orienting the board",
                       "At every new station the board must be turned until the drawn line between the two stations lies along the real one. Get that wrong and the survey is beautifully consistent and completely false.")]),
    ChartSpec(id: "hallow_delta", name: "Hallow Delta", place: "River mouth", year: "1864",
              kind: "delta", scaleNote: "Cables", kicker: "Sheet XII",
              notes: [("Offsets from a chain line",
                       "Run the chain along a straight line and measure short right-angled offsets to the bank at every change of direction. It is the cheapest survey there is and it is exactly how field boundaries were mapped for two centuries."),
                      ("Where the water goes",
                       "A delta channel silts and swings. Surveyors mark the deep channel with a dotted line and add the year, knowing that the next man will find it somewhere else.")]),
    ChartSpec(id: "north_ness", name: "North Ness", place: "Northern isles", year: "1866",
              kind: "cape", scaleNote: "Sea miles", kicker: "Sheet XIII",
              notes: [("Magnetic variation",
                       "The compass does not point north and the difference changes from place to place and year to year. The rose carries both norths and the annual change, which is why an old chart's bearings need correcting before use."),
                      ("Station marks",
                       "A surveyed station is cut into rock, buried as a stone, or piled as a cairn, so the next survey can stand exactly where this one stood. Some marks on northern headlands have been found and re-used a century later.")]),
    ChartSpec(id: "lammer_bay", name: "Lammer Bay", place: "Eastern coast", year: "1844",
              kind: "bay", scaleNote: "Cables", kicker: "Sheet XIV",
              notes: [("The cocked hat",
                       "Three bearings to three known objects should meet in a point and never do. The little triangle they make is the cocked hat, and a careful surveyor assumes he is at its worst corner, not its middle."),
                      ("Angles beat bearings",
                       "A compass bearing carries the compass's own errors. Measuring the angle between two objects with a sextant carries almost none, which is why coastal fixing was done with a sextant held horizontally.")]),
    ChartSpec(id: "quarry_isle", name: "Quarry Isle", place: "Granite island", year: "1853",
              kind: "island", scaleNote: "Cables", kicker: "Sheet XV",
              notes: [("Copper, and the reason the lines are so fine",
                       "Charts were engraved in reverse on copper with a burin. A line could be made as fine as a hair and re-cut when it wore, which is why nineteenth-century charts hold detail no lithograph could."),
                      ("Corrections by hand",
                       "A new danger did not mean a new plate. The correction was punched into the copper and the printed sheets were amended in red ink by hand in the chart office.")]),
    ChartSpec(id: "faither_fjord", name: "The Faither", place: "Deep inlet", year: "1869",
              kind: "fjord", scaleNote: "Cables", kicker: "Sheet XVI",
              notes: [("Deep water is harder than shallow",
                       "A hand lead reaches about twenty fathoms. Beyond that the deep-sea lead needs the ship stopped, a heavy weight and a long, cold hour, so deep soundings on an old chart are far fewer and far more precious."),
                      ("The sounding machine",
                       "Wire instead of rope and a pressure tube instead of a bottom feel let a ship sound while under way. It changed offshore surveying more than any instrument since the sextant.")]),
]

let chartBookC: [ChartSpec] = [
    ChartSpec(id: "dorn_narrows", name: "Dorn Narrows", place: "Tidal narrows", year: "1858",
              kind: "sound", scaleNote: "Cables", kicker: "Sheet XVII",
              notes: [("Running survey",
                       "A ship passing a coast can chart it without landing: bearings of headlands taken at intervals, the run between them measured by log, and the whole strung together. It is quick, it is rough, and most first charts of a coast were made this way."),
                      ("What a running survey misses",
                       "Everything behind the first line of hills, and every rock that did not show on the day. The next survey is always ashore with a theodolite, and always finds more.")]),
    ChartSpec(id: "the_saltings", name: "The Saltings", place: "Marsh and creek", year: "1847",
              kind: "estuary", scaleNote: "Furlongs", kicker: "Sheet XVIII",
              notes: [("Conventional signs",
                       "Marsh is a tuft with two short strokes, rough pasture a scatter of dots, wood a cluster of small crowns. The signs are drawn small and repeated, never outlined as areas, so the eye reads texture rather than shape."),
                      ("Creeks in a marsh",
                       "They are drawn to their real width because at high water they are navigable and at low water they are a trap. The surveyor walked them at low water with a pole.")]),
    ChartSpec(id: "the_mewstone", name: "The Mewstone", place: "Approach mark", year: "1862",
              kind: "island", scaleNote: "Cables", kicker: "Sheet XIX",
              notes: [("Views on the sheet",
                       "Old charts carry small coastal profiles along the border: what the land looks like from seaward at a stated bearing and distance. For a stranger making a landfall, that little drawing is worth the whole survey."),
                      ("Drawn, not sketched",
                       "The profile is taken with the sextant too — the height of the hill above the horizon measured, the outline traced against a ruled line, so that the picture is a measurement and not an impression.")]),
    ChartSpec(id: "broad_water", name: "Broad Water", place: "Shallow bay", year: "1851",
              kind: "bay", scaleNote: "Cables", kicker: "Sheet XX",
              notes: [("The lead line itself",
                       "Marked at two, three, five, seven, ten, thirteen, fifteen, seventeen and twenty fathoms in leather, calico and cord, so the leadsman can read it by feel in the dark. Anything unmarked is a deep and called by guess."),
                      ("Arming the lead",
                       "Tallow in the hollow base brings up sand, shell or mud. The bottom quality is printed on the chart beside the sounding, and a master in fog navigates by what comes up on the tallow.")]),
    ChartSpec(id: "calder_mouth", name: "Calder Mouth", place: "Bar harbour", year: "1867",
              kind: "estuary", scaleNote: "Cables", kicker: "Sheet XXI",
              notes: [("The bar",
                       "Where a river's silt meets the sea's swell there is a shoal across the entrance, and it is shallowest exactly where everyone must cross. A bar harbour's chart is mostly about the hour of the tide."),
                      ("Traverse and closure",
                       "The chain line up a winding river is a traverse: distances and angles, leg after leg. Compute round the whole circuit and it should return to the starting point; whatever it misses by is spread back through the legs.")]),
    ChartSpec(id: "hoy_skerries", name: "Hoy Skerries", place: "Outlying rocks", year: "1871",
              kind: "reef", scaleNote: "Sea miles", kicker: "Sheet XXII",
              notes: [("Why rocks get an ornamental name",
                       "A skerry has no shape worth drawing and is deadly. The chart gives it a name, a symbol and a clearing bearing, and the name is what a helmsman remembers at two in the morning."),
                      ("Clearing marks",
                       "Keep the church open west of the cliff and you pass outside the reef. A clearing mark is a piece of surveying that needs no instrument at all, and it has saved more ships than any beacon.")]),
    ChartSpec(id: "penhale_cove", name: "Penhale Cove", place: "Boat cove", year: "1849",
              kind: "harbour", scaleNote: "Cables", kicker: "Sheet XXIII",
              notes: [("The small sheet",
                       "A cove that takes six boats still gets a plan at a large scale, because the scale of a chart is set by the danger and not by the importance of the place."),
                      ("Drawn twice",
                       "Everything is drawn in pencil in the field and inked in the office from the field book. The field book, not the drawing, is the record, and it is what an argument is settled from years later.")]),
    ChartSpec(id: "white_horse_bank", name: "White Horse Bank", place: "Offshore shoal", year: "1873",
              kind: "reef", scaleNote: "Sea miles", kicker: "Sheet XXIV",
              notes: [("Naming a shoal from the sea",
                       "The white water over a shoal in a swell is what names it, and the name is generally older than any chart. Surveyors kept those names deliberately: they are a description of the danger."),
                      ("The last thing on the plate",
                       "Title, authority, date, scale, datum and the surveyor's name go in the cartouche, and they are engraved last, when nothing on the sheet is going to change again.")]),
]
